name: Deploy Portfolio

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Rebuild Backend
        run: |
          docker compose up -d --build

      - name: Update Nginx Files
        run: |
          # Création du dossier de destination s'il n'existe pas
          mkdir -p /DATA/AppData/mesSites/portfolio_tom/frontend/dist/
          # Copie des fichiers sans sudo (nécessite que jolan soit proprio du dossier)
          cp -r frontend/dist/* /DATA/AppData/mesSites/portfolio_tom/frontend/dist/
