name: Deploy Portfolio

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Production Folder
        run: |
          mkdir -p /DATA/AppData/mesSites/portfolio_tom
          # Copie récursive du code vers le dossier final
          # On ne copie pas .git pour éviter les soucis
          rsync -av --exclude '.git' . /DATA/AppData/mesSites/portfolio_tom/
          
      - name: Rebuild Backend
        run: |
          cd /DATA/AppData/mesSites/portfolio_tom
          # On crée un .env si absent
          if [ ! -f backend/.env ]; then touch backend/.env; fi
          docker compose up -d --build
